/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-delta-payroll-kbkgohT9AtZAOyGYdV5QqycSu17S-xk5",
  "version": "2020-11-20"
}

export default ebconfig;
